
CREATE USER "GPAY" IDENTIFIED BY "GpayPass009" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP" ;
GRANT CREATE SESSION TO "GPAY";
GRANT ALL PRIVILEGES TO "GPAY";
GRANT UNLIMITED TABLESPACE TO "GPAY";
